### ISSUE TITLE
Toolbar icons do not have tooltips

### ISSUE THREAD

**Issue by waddlesplash** [HaikuArchives/DocumentViewer#12]
Some of them are not so obvious as to what they do, so it'd be nice to have tooltips.

**Comment by R4H33M** [comment]
I'd like to claim this one.

**Comment by owenca** [comment]
You should claim tasks on the GCI website. You can't pre-claim tasks on GitHub while your current task is being reviewed.

**Comment by R4H33M** [comment]
Alright. I wasn't aware of this. I won't pre-claim tasks anymore.
