### ISSUE TITLE
Broken UI and crash when opening PDF file

### ISSUE THREAD

**Issue by Akujiism** [HaikuArchives/DocumentViewer#19]
I'm not sure whether this is already reflected in other tickets, nevertheless decided to mention:
- broken UI in current version (0.3), see the screenshot attached
- crash when trying to open a file (EN user guide of BePDF), see debug report attached
  ![document-viewer](https://cloud.githubusercontent.com/assets/5451848/15702664/ed03ce06-27e9-11e6-8107-ff06f1c32923.png)

**Comment by Akujiism** [comment]
[DocumentViewer-1092-debug-31-05-2016-20-16-29.zip](https://github.com/HaikuArchives/DocumentViewer/files/292932/DocumentViewer-1092-debug-31-05-2016-20-16-29.zip)

**Comment by owenca** [comment]
The crash is caused by dereferencing a null pointer, and it seems that it happens with opening any file.

**Comment by waddlesplash** [comment]
The UI isn't broken, that's just what it looks like when no file is open....

**Comment by waddlesplash** [comment]
https://github.com/HaikuArchives/DocumentViewer/commit/7415c8c3f76cf1d89eca21d97400a3363f7e8b77
https://github.com/HaikuArchives/DocumentViewer/commit/1b299cd4bdc0d6d1d2acc80fd4b7c970dc3a33ab
