### ISSUE TITLE
Add tooltips for tab icons

### ISSUE THREAD

**Issue by R4H33M** [HaikuArchives/DocumentViewer#30]
The tab images could do with some tooltips. But since they use custom drawing code, it might be tricky to implement this. BView::SetToolTip isn't applicable here, unless one creates artifical BViews over each icon. I tried that and got many strange bugs, but maybe someone else could figure it out?

If it proves to complicated, we could potentially switch to text on the tabs, as is done in Adobe Acrobat DC.

**Comment by owenca** [comment]
Probably a better approach is to use the `MouseMoved `hook method.

**Comment by R4H33M** [comment]
In that case, it won't be a native tooltip, right? So we will draw our own?

**Comment by owenca** [comment]
You probably can just use `BView::SetToolTip` with `MouseMoved`. If you want to try it, we can create a **Fix an open issue in DocumentViewer [1]** task.

**Comment by R4H33M** [comment]
That sounds like it could work...
I'll try it out, but no guarantees. ;)

**Comment by owenca** [comment]
> If you want to try it, we can create a **Fix an open issue in DocumentViewer [1]** task.

We have published the task.

**Comment by R4H33M** [comment]
Perfect. :)
