### ISSUE TITLE
DocumentViewer freezes (no response when opening a pdf file)

### ISSUE THREAD

**Issue by Begasus** [HaikuArchives/DocumentViewer#39]
![Document-Viewer](https://user-images.githubusercontent.com/16057090/133833470-8aec91ea-0e3c-4ea7-bc95-4028c9b10211.png)
After checking up on latest push in the source I wanted to check out a new build, the app launches fine, but freezes without response ...

**Comment by Begasus** [comment]
Seems to be fixed, this one can be closed for me. :)

**Comment by humdingerb** [comment]
A self-healing app?

**Comment by waddlesplash** [comment]
Probably the muPDF upgrades over the last year fixed it.
