### ISSUE TITLE
DocumentViewer 0.3_git-4 is not able to open some PDF files: has a strange behaviour.

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/DocumentViewer#5]
I have recently updated DocumentViewer to the last available version: 0.3_git-4.
Well, this version, (although if i delete the "RecentlyOpened" file as described in ticket https://github.com/HaikuArchives/DocumentViewer/issues/2), is unable to load some PDF files. In anyway i have noticed a very strange behaviour: if I open a PDF file which contains only text and some graphics, the next time DocumentViewer will be able to open these PDF file (which I link below to this message), and in this case i can see that the file "Apps" is created under "/boot/home/config/settings/Apps": this configuration file, instead, is not created if i open "problematic" PDF files.

If i delete the file "/boot/home/config/settings/Apps/Apps" (which is not created the first time that i attempt to open these "problematic" PDF files), DocumentViewer is still unable to open these PDF files (which contain images). But if i delete "/boot/home/config/settings/Apps/Apps", DocumentViewer will be able to open PDF files which contains only text and some graphics, and the file "/boot/home/config/settings/Apps/Apps" will be created (is created only with simple PDF files").
I hope to have been clear, since this behaviour is very odd, and I'm not very good to express myself in english.

In anyway these are PDF files which DocumentViewer can't open at the first attempt (eg with a  fresh install, and so with the directory "/boot/home/config/settings/Apps/" empty)

ftp://files.dlink.com.au/products/DIR-300/REV_A/SetupGuides/How_to_setup_Port_Forwarding_in_DIR-300.pdf

http://www.dlink.com/-/media/Consumer_Products/DIR/DIR 300/Manual/DIR_300_Manual_v_2_00_en_uk.pdf

**Comment by diversys** [comment]
Doesn't crash anymore. Was probably the same problem as in #9.
