### ISSUE TITLE
Multiple PDFs in the PDFjs Testsuite crash DocumentViewer

### ISSUE THREAD

**Issue by waddlesplash** [HaikuArchives/DocumentViewer#9]
At least `tracemonkey.pdf`, `freeculture.pdf`, `TAMReview.pdf`, and `S2.pdf` all crash it. I stopped testing after that.

I don't know what these files all have in common (I know most of them are multipage, but I don't think that's the issue...)

**Comment by diversys** [comment]
These files don't crash DV anymore. I can only guess that the bug was in builtin MuPDF libs (libjpeg, etc) which it no longer uses.
